### ISSUE TITLE
[roadmap] Alfa checklist

### ISSUE THREAD

**Issue by pkarw** [CatchTheTornado/doctor-dok#51]
- [x]  Prompts for the prompt library
- [x]  Make it act as OCR - in addition to JSON, extract the original text exactly as it is in the documentation
- [x]  Specify the extraction format more detailed and include that if medications are listed, extract them too; provide available code labels
- [x]  Dictionary with label translations for display - should be in the same file for editing as prompts
- [x]  Generic method for extracting additional items to "extra" or "json" (fields must have the same type - type it in JavaScript) - examples of such content can be provided in the prompt - through this method, it will be easy to add more actions
- [x]  Method for extracting attachments should also be written as a generic action to be triggered and triggered by the icon with inserting into chat or the icon with refreshing where we also ask for a prompt
- [x]  Separate icon for interpreting results - remove this from the original prompt, there should only be JSON + OCR parsing
- [x]  Save the language of the record in the "language" field of JSON and do not translate to English
- [x]  Save this markdown text in an additional field in the database named "text" or "markdown" - probably better
- [x]  Extra can have this format: [{"type": "remarks", "value": ""}]
- [x]  Save the interpretation result in the "remarks" field in "extra"
- [x]  Display records with extra in the same accordion as records with JSON
- [x]  Display JSON records in chat - nicely
- [x] #80
- [x] #81
- [x]  Automatically set record.type when saving
- [x] #77
- [x] #76
- [x]  Wrapping images in chat
- [x]  Display images in records
- [x]  Vector logo
- [x] #88
- [x] #78
- [x] #85
- [x]  Short demo video
- [x] #83
- [x] #84
- [x] Blacklisted PII redaction #73
- [x] Extend patient data #75 
- [x] Sharing feature - bc. it requires db architecture change and config encoding change - #52
